name: Basic CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    NODE_VERSION: 20.x
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Environment ( ${{ env.NODE_VERSION }} )
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Install dependencies
              run: npm ci

            - name: Build package
              run: npm run build

    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Environment ( ${{ env.NODE_VERSION }} )
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Install dependencies
              run: npm ci

            - run: npm run lint

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Environment ( ${{ env.NODE_VERSION }} )
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Install dependencies
              run: npm ci

            - run: npm run test

    dependabot-auto-merge:
        runs-on: ubuntu-latest
        needs:
            - test
            - build
            - lint
        if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
        steps:
            - name: automerge
              uses: actions/github-script@v7
              with:
                  script: |
                      github.pullRequests.createReview({
                          owner: context.payload.repository.owner.login,
                          repo: context.payload.repository.name,
                          pull_number: context.payload.pull_request.number,
                          event: 'APPROVE'
                      })

                      github.pullRequests.merge({
                          owner: context.payload.repository.owner.login,
                          repo: context.payload.repository.name,
                          pull_number: context.payload.pull_request.number
                      })
                  github-token: ${{ env.GITHUB_TOKEN }}
