name: Basic CI

on: pull_request

env:
    NODE_VERSION: 16.x

jobs:
    # build:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/checkout@v2

    #         - name: Setup Environment ( ${{ env.NODE_VERSION }} )
    #           uses: actions/setup-node@v2
    #           with:
    #               node-version: ${{ env.NODE_VERSION }}

    #         - name: Install dependencies
    #           run: npm ci

    #         - name: Build package
    #           run: npm run build

    # lint:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/checkout@v2

    #         - name: Setup Environment ( ${{ env.NODE_VERSION }} )
    #           uses: actions/setup-node@v2
    #           with:
    #               node-version: ${{ env.NODE_VERSION }}

    #         - name: Install dependencies
    #           run: npm ci

    #         - run: npm run lint

    # test:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/checkout@v2

    #         - name: Setup Environment ( ${{ env.NODE_VERSION }} )
    #           uses: actions/setup-node@v2
    #           with:
    #               node-version: ${{ env.NODE_VERSION }}

    #         - name: Install dependencies
    #           run: npm ci

    #         - run: npm run test
    pr_check:
        name: Bot reviewer
        runs-on: ubuntu-latest
        steps:
            - name: Check who make the commit
              run: |
                  # check commit id with base
                  # if same id || coming from bot -> no dismiss
                  # else dismiss

                  echo ${{ github.event.pull_request.head.user.email }}

                  # isBot=0
                  # if [[ ${{ github.event.pull_request.head.user.email }} == *"@users.noreply.github.com"* ]]; then
                  #   isBot=1
                  # fi

                  isMerged=0
                  if [[ ${{ github.event.pull_request.base.ref }} != ${{ github.event.pull_request.head.ref }} ]]; then
                    isMerged=1
                  fi

                  # echo "isBot:"
                  # echo $isBot

                  echo "isMerged:"
                  echo $isMerged

                  echo "base commit sha:"
                  echo ${{ github.event.pull_request.base.ref }}

                  echo "target commit sha:"
                  echo ${{ github.event.pull_request.head.ref }}

                  # if [ ${{ github.event.ref }} != 'refs/heads/main' ]; then
                  #   gh api /repos/${{ github.repository }}/pulls/${{ github.event.number }}/reviews/{{review_id}}/dismissals -d '{"message":"An update has been made, you need to review again! :eyes:","event":"DISMISS"}'
                  # fi
