name: RELEASE

on:
    release:
        types:
            - released

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    deployment:
        name: Prod deployemnt
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Environment ( ${{ env.NODE_VERSION }} )
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Fetch the download url from the release file
              env:
                  RELEASE: ${{ toJSON(github.event.release) }}
                  PACKAGE_VERSION: ${{ github.event.release.tag_name }}
              run: |
                  downloadUrl=$(jq -r -n --argjson PACKAGE_VERSION "$PACKAGE_VERSION" --argjson data "$RELEASE" '$data.assets[] | select(.name=="conversational-commerce-$PACKAGE_VERSION.zip").browser_download_url')
                  cd ./dist && mkdir tmp
                  wget -O ./dist/tmp/conversational-commerce-$PACKAGE_VERSION.zip $downloadUrl

            - name: Download the release file
              run: |
                  ls -la ./dist/tmp
