name: RELEASE

on:
    release:
        types:
            - released

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    deployment:
        name: Prod deployemnt
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Environment ( ${{ env.NODE_VERSION }} )
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Fetch the download url from the release file
              run: |
                  ${{ toJson(github.event.release) }} > event.json
                  downloadUrl=$(jq --raw-output '.assets[] | select(.name=="conversational-commerce-2.0.zip").download_url' event.json
                  echo $downloadUrl
                  cd ./dist && mkdir tmp
                  wget -O ./dist/tmp/conversational-commerce-2.0.zip $downloadUrl

            - name: Download the release file
              run: |
                  ls -la ./dist/tmp
